apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    app: ds6-user-service
type: Opaque
# IMPORTANTE: Os valores abaixo DEVEM ser codificados em Base64.
# Use o comando: echo -n 'seu-valor-aqui' | base64
# Exemplo para 'postgres': echo -n 'postgres' | base64 -> cG9zdGdyZXM=
data:
  # Usuário do banco de dados
  DB_USER: "cG9zdGdyZXM=" # Valor para 'postgres'
  # Senha do banco de dados
  DB_PASSWORD: "c3VhX3NlbmhhX2FxdWk=" # Valor para 'sua_senha_aqui'
  # Chave secreta para assinar os tokens JWT
  JWT_SECRET: "NkFCTTNBZ0hxTGFhUS9XRHQzUWpUUTZ3Tzk5WVJYTlJVaGpKalZmaEgrdz0=" # Valor para '6ABM8AgHqlaaQ/WDtQqJTQ6wO99YRXNRUhjJjVfbH+w='
