name: 'CI/CD Pipeline Principal'

on:
  push:
    branches:
      - 'main'

jobs:
  call-reusable-workflow:
    uses: ./.github/.github/workflows/reusable-java-k8s-pipeline.yml
    permissions:
      contents: read
      packages: write
    with:
      service-name: 'ds6-user-service'
    secrets:
      inherit
